<?php
/**
 * A little more complex example of how you can define a "Book" with some additional parameters.
 */ 
class BookSkeleton extends Entity
{
	public function __construct()
	{
		parent::__construct('ormskeleton','bookskeleton');
		
		$this->add(new Field('book_id'	
			, CAST::$INTEGER 
			, null	
			, null 		
			, KEY::$PK	
		));
		
		$this->add(new Field('title'	
			, CAST::$STRING
			, 50	
		));
		
		$this->add(new Field('description'	
			, CAST::$STRING
			, 255	
		));
		
		// This is a UUID : a varchar(32) in database
		// Used to store a UUID : a unique id generated by the system itself. 
		//  example : CORE::generateUUID();
		$this->add(new Field('uuid'		
			, CAST::$UUID
		));
		
		// Now we'll add more informations on our Entity
		// 1] we want to use the Mysql system auto-increment instead using a table xxx_seq like CmsMadeSimple does
		$this->garnishAutoincrement();
		
		// 2] we want to be sure that the title is Unique.
		$this->garnishUniqueKeys(array('title'));
		
		// 3] We will propose a default value for the description Field
		$this->garnishDefaultValue('description',"It's a great Book");
	}	
}
?>